from os import getenv

CONSUMER_KEY        = getenv("CONSUMER_KEY")
CONSUMER_SECRET     = getenv("CONSUMER_SECRET")
ACCESS_TOKEN        = getenv("ACCESS_TOKEN")
ACCESS_TOKEN_SECRET = getenv("ACCESS_TOKEN_SECRET")
BEARER_TOKEN        = getenv("BEARER_TOKEN")
IMGUR_CLIENTID      = getenv("IMGUR_CLIENTID")
IMGUR_SECRET        = getenv("IMGUR_SECRET")
IMGUR_REFRESH_TOKEN = getenv("IMGUR_REFRESH_TOKEN")
IMGUR_ACCESS_TOKEN  = getenv("IMGUR_ACCESS_TOKEN")
POLYGONSCAN_API_KEY = getenv("POLYGONSCAN_API_KEY")
WEB3_STORAGE_API    = getenv("WEB3_STORAGE_API")